apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb" 
spec:
  selector:
    app: appointment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
