name: Build Docker Image, Push Docker Images, and Deploy to EKS
run-name: Build, Push Docker Images & Deploy to EKS

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Amazon ECR
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      env:
         AWS_REGION: ${{ secrets.AWS_REGION }}
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Build, tag, and push Docker image for Patient Service
    - name: Build, Tag & Push Docker Image for Patient Service
      run: |
        cd ./app/patient-svc/
        docker build -t patient-service:latest -f Dockerfile .
        docker tag patient-service:latest 677276078111.dkr.ecr.us-east-1.amazonaws.com/my-app-repo:patient-service-latest
        docker push 677276078111.dkr.ecr.us-east-1.amazonaws.com/my-app-repo:patient-service-latest

    # Build, tag, and push Docker image for Appointment Service
    - name: Build, Tag & Push Docker Image for Appointment Service
      run: |
        cd ./app/appointment-svc/
        docker build -t appointment-service:latest -f Dockerfile .
        docker tag appointment-service:latest 677276078111.dkr.ecr.us-east-1.amazonaws.com/my-app-repo:appointment-service-latest
        docker push 677276078111.dkr.ecr.us-east-1.amazonaws.com/my-app-repo:appointment-service-latest

    # Set up AWS credentials for kubectl to use
    - name: Configure AWS Credentials for kubectl
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Set up kubectl
    - name: Set up kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/v1.27.0/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    # Get EKS Cluster credentials for kubectl
    - name: Configure kubectl for EKS
      run: |
        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

    # Deploy Patient Service to Kubernetes
    - name: Deploy Patient Service to Kubernetes
      run: |
        cd ./app/k8s
        kubectl apply -f pat-deployment.yaml
        kubectl apply -f pat-service.yaml
        kubectl apply -f ingress-controller.yaml

    # Deploy Appointment Service to Kubernetes
    - name: Deploy Appointment Service to Kubernetes
      run: |
        cd ./app/k8s
        kubectl apply -f app-deployment.yaml
        kubectl apply -f app-service.yaml
        kubectl apply -f ingress-controller.yaml
